# Generated by Django 4.2.21 on 2025-05-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Маркетплейс',
                'verbose_name_plural': 'Маркетплейсы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Главный баннер'), ('about', 'О компании'), ('customs', 'Таможенное оформление'), ('permits', 'Разрешительная документация'), ('classification', 'Классификация и защита интересов'), ('advantages', 'Преимущества'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Тип секции')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержимое')),
                ('background_image', models.URLField(blank=True, max_length=500, verbose_name='Фоновое изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Секция страницы',
                'verbose_name_plural': 'Секции страниц',
                'ordering': ['section_type'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('icon', models.CharField(choices=[('document', 'Документ'), ('wallet', 'Кошелек'), ('lamp-charge', 'Лампочка с молнией'), ('security', 'Безопасность'), ('note', 'Заметка'), ('autotransport', 'Автотранспорт'), ('case', 'Портфель'), ('checkmark', 'Галочка')], default='document', max_length=50, verbose_name='Иконка')),
                ('section', models.CharField(choices=[('customs', 'Таможенное оформление'), ('permits', 'Разрешительная документация'), ('classification', 'Классификация и защита интересов')], default='customs', max_length=50, verbose_name='Раздел')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['section', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='КАРГОСТАР', max_length=100, verbose_name='Название сайта')),
                ('site_description', models.TextField(default='Комплексные решения в сфере ВЭД, сертификации и таможенного оформления', verbose_name='Описание сайта')),
                ('logo_url', models.URLField(blank=True, max_length=500, verbose_name='URL логотипа')),
                ('email', models.EmailField(default='mail@kargostar.ru', max_length=254, verbose_name='Email')),
                ('phone_1', models.CharField(default='+7 (905) 273-10-25', max_length=20, verbose_name='Телефон 1')),
                ('phone_2', models.CharField(blank=True, default='+7 (905) 234-19-59', max_length=20, verbose_name='Телефон 2')),
                ('phone_3', models.CharField(blank=True, default='+7 (921) 565-36-41', max_length=20, verbose_name='Телефон 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
